<a href="https://colab.research.google.com/github/Yosef-Mekuria/PyTorch-Tutorial/blob/main/PyTorch_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR:**
- is multidimensional or one dimensional matrix containing elements of one/same data type
- is primary data structure in pytorch
- is suitable for Deep Learning

In [8]:
import torch

In [14]:
#Here we create a simple tensor by passing python list to tensor method
new_tensor = torch.tensor([1, 2, 3, 4 , 5])
new_tensor

tensor([1, 2, 3, 4, 5])

In [15]:
my_list = [6, 7, 8]
new_tensor2 = torch.tensor(my_list)
new_tensor2

tensor([6, 7, 8])

In [17]:
#Checking the data type of the new_tensor
new_tensor.dtype

torch.int64

In [18]:
#Here we create a simple tensor by passing numpy array to from_numpy method
import numpy as np
np_arr= np.array([1, 2, 3, 4])
tensor_from_np = torch.from_numpy(np_arr)
tensor_from_np

tensor([1, 2, 3, 4])

In [19]:
tensor_from_np.dtype

torch.int64

In [23]:
#Creating a tensor of Zero square matrix with shape of 3
zero_matrix = torch.zeros(3, 3)
zero_matrix

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
#Creating a tensor of square matrix with entries of one and shape of 2
one_matrix = torch.ones(2, 2)
one_matrix

tensor([[1., 1.],
        [1., 1.]])

In [25]:
second_one_matrix = torch.ones(2, 2)
second_one_matrix

tensor([[1., 1.],
        [1., 1.]])

In [30]:
#Creating a tensor with arange method, this method returns elements starting from 0 to n (the argument we passed) but not including n.
new_tensor_range = torch.arange(10)
new_tensor_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**TENSOR OPERATIONS**

In the code cells below we see how we perform different operations on the tensor data.
- Tensor addition
- Tensor subtraction
- Element wise tensor multiplication
- Reshaping tensor

In [43]:
#Performing tensor operations
#this is element-wise multiplication

print(one_matrix + second_one_matrix)
print(one_matrix - second_one_matrix)
print(one_matrix * second_one_matrix)
print(one_matrix / second_one_matrix)
print(one_matrix % second_one_matrix)

tensor([[2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [31]:
#The arguments we pass to reshape method should be able to fit the data, other wise we encounter an error
reshaped_tensor = new_tensor_range.reshape(2, 5)
reshaped_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#this is an error because we have 10 elements but we set the reshape to contain 8 elements
reshaped_tensor = new_tensor_range.reshape(2, 4)

In [34]:
reshaped_tensor_with_view = new_tensor_range.view(5, 2)
reshaped_tensor_with_view

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
#To reshape we can also specify the row/column value only and let the other value be identified automatically by passing -1
reshaped_tensor = new_tensor_range.reshape(2, -1)
reshaped_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Slicing**

- Slicing using index, remember index starts from 0

In [36]:
new_tensor3 = torch.arange(100)
new_tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
new_tensor3 = new_tensor3.reshape(10, 10)
new_tensor3

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
#Slicing, grabing the 0th, 1st rows excluding the rest
print(new_tensor3[0:2])

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


In [40]:
#Slicing, grabing the 0th, 1st rows and 0th, 1st columns excluding the rest
print(new_tensor3[0:2,0:2])

tensor([[ 0,  1],
        [10, 11]])


In [41]:
#Slicing, grabing all rows starting from the 0th row and 0th, 1st columns excluding the rest
print(new_tensor3[0:,0:2])

tensor([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41],
        [50, 51],
        [60, 61],
        [70, 71],
        [80, 81],
        [90, 91]])


... and more.